#!/usr/bin/env ruby

require 'jirgit'
require 'launchy'

@log = Jirgit::Logger.new(".git/jirgit/hooks.log")
@log.hook = File.basename $0
@log.level = Logger::DEBUG

@log.debug "launched"

@config = Jirgit::Configuration.new("#{`echo ~`.chomp}/.jirgit")

def current_branch
  @current_branch ||= begin
    branch = Jirgit::Git.current_branch
    @log.debug "#{__method__} #{branch}"
    branch
  end
end

def current_commit
  @current_commit ||= begin
    commit = Jirgit::Git.current_commit
    @log.debug "#{__method__} #{commit}"
    commit
  end
end

def jira_store
  @jira_store ||= Jirgit::JiraStore.new(".git/jirgit/jira_store")
end

def related_jiras(params)
  jira_store
    .relations(params)
    .to_a
    .select { |r| r.type == :jira }
    .map(&:label)
end

def relate_commit_to_current_branch
  jira_store.relate(commit: current_commit, branch: current_branch)
end

def relate_commit_to_jiras_for_current_branch
  related_jiras(branch: current_branch).each do |jira|
    jira_store.relate(jira: jira, commit: current_commit)
  end
end

def open_jira_in_browser
  if @config[:open_jira]
    related_jiras(branch: current_branch).each do |jira|
      Launchy.open("#{@config[:jira_url]}/browse/#{jira}")
    end
  end
end

relate_commit_to_current_branch
relate_commit_to_jiras_for_current_branch
open_jira_in_browser

